# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='A product', max_length=30),
        ),
    ]
