# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Empty description', max_length=400),
        ),
    ]
