# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default=['OneSize'], max_length=30),
        ),
    ]
