# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(default='Empty url', max_length=200),
            preserve_default=False,
        ),
    ]
