# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_orderdelivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orderDelivered',
        ),
    ]
