# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('order_number', models.IntegerField()),
                ('order', models.TextField(max_length=1000)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2017, 11, 16, 10, 32, 55, 760579))),
                ('orderDelivered', models.BooleanField(default=False)),
            ],
        ),
    ]
