# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 10, 33, 19, 223759)),
        ),
    ]
