# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20171116_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 29, 10, 53, 10, 242166)),
        ),
    ]
