# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 9, 19, 12, 8, 47, 497495)),
        ),
    ]
