# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 9, 19, 12, 6, 29, 661178)),
        ),
    ]
