# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20170919_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 20, 11, 50, 362893)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.TextField(max_length=1000),
        ),
    ]
